### ISSUE TITLE
No hyperlink support in "Details" view

### ISSUE THREAD

**Issue by sagarhani** [pythonindia/PyConIndiaAndroid#1]
![pycon-android](https://cloud.githubusercontent.com/assets/6933389/10169304/14c8ccce-66ee-11e5-8242-91c9cc52e403.png)
## 
- Hyperlinks are not supported.
- Also, It is not possible to copy the text/url also. 

Either one of the support is needed

**Comment by abhi1992** [comment]
does long press on details not bring up the copy paste options? Which version of android are u using? We are going to change those urls on server side. 
Thanks!

**Comment by sagarhani** [comment]
Okay. Long press gives me copy paste options. :+1:

**Comment by abhi1992** [comment]
I'm closing this case.
