### ISSUE TITLE
Feedback form - unable to unselect the options

### ISSUE THREAD

**Issue by sagarhani** [pythonindia/PyConIndiaAndroid#2]
![pycon-feedback](https://cloud.githubusercontent.com/assets/6933389/10169812/73ea400a-66f0-11e5-9bf3-26c36f0804e4.png)
## 

If you select one of the options by mistake, you cannot unselect it again.

**Comment by abhi1992** [comment]
uploaded a fix can you check it again @sagarhani ? 
Thanks!

**Comment by sagarhani** [comment]
@abhi1992 Should install from play store and check this ?
I guess it is not updated on play store, it shows last updated on - `25 Sep 2015` (version 1.0.1)

**Comment by abhi1992** [comment]
@sagarhani It will be available in some time. Thanks for the help.

**Comment by sagarhani** [comment]
@abhi1992 I'll test once it gets updated on play store. :+1:

**Comment by abhi1992** [comment]
It's up @sagarhani

**Comment by sagarhani** [comment]
@abhi1992 it works perfect now. :+1:

**Comment by abhi1992** [comment]
ok case closed.
